-- This file is sourced from https://github.com/open-sauced/api/tree/beta/migrations
-- and is used only for local development convenience

------------------------------------
-- Pizza oven "baked" repos table --
-------------------------------------
create table if not exists public.baked_repos
(
  id bigint not null generated by default as identity ( increment 1 start 1 minvalue 1 maxvalue 9223372036854775807 cache 1 ),
  clone_url character varying(255) collate pg_catalog."default" not null,

  -- elastic columns

  -- the repo_id field is used to loosely reference an id from the repos table
  -- but since git repos may have their commits indexed that have not yet been
  -- indexed into the repos table, there is not direct correlation.
  -- Joins can happen across the "clone_url" to find repos that have not yet
  -- synced to baked_repos.
  repo_id bigint default null,

  -- dynamic columns
  constraint baked_repos_pkey primary key (id)
)

tablespace pg_default;

-- indexes for baked repos
create index if not exists baked_repos_idx_clone_url on baked_repos (clone_url);

-------------------------------------
-- Pizza oven commit authors table --
-------------------------------------
create table if not exists public.commit_authors
(
  id bigint not null generated by default as identity ( increment 1 start 1 minvalue 1 maxvalue 9223372036854775807 cache 1 ),
  commit_author_email character varying(255) collate pg_catalog."default" not null,

  -- dynamic columns
  constraint commit_authors_pkey primary key (id)
)

tablespace pg_default;

-- indexes for baked repos
create index if not exists commit_authors_idx_commit_author_email on commit_authors (commit_author_email);

--------------------------------
-- Pizza oven indexed commits --
--------------------------------

create table if not exists public.commits (
  id bigint not null generated by default as identity ( increment 1 start 1 minvalue 1 maxvalue 9223372036854775807 cache 1 ),
  baked_repo_id bigint not null references public.baked_repos (id) on delete cascade on update cascade,
  commit_author_id bigint not null references public.commit_authors(id) on delete cascade on update cascade,
  commit_hash character varying(255) collate pg_catalog."default" not null,
  commit_date timestamp with time zone not null default now(),

  -- dynamic columns
  constraint commits_pkey primary key (id)
)

tablespace pg_default;

-- psql indexes for commits
create index if not exists commit_idx_hash on commits (commit_hash);
create index if not exists commit_idx_date on commits (commit_date);

